/// Categoría de discapacidad.
enum DisabilityCategory {
  PHYSICAL_DISABILITY,
  VISUAL_DISABILITY,
  HEARING_DISABILITY,
  INTELLECTUAL_DISABILITY,
  PSYCHOSOCIAL_DISABILITY,
  DEAFBLINDNESS,
  MULTIPLE_DISABILITY,
  NO_DISABILITY,
}
